#version: "3.7"
#
#services:
#  passenger-service:
#    image: myc0dinghub/passenger-service:0.0.1
#    ports:
#      - 8082:8082
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/passengerdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=12345
#    depends_on:
#      - db
#  db:
#    container_name: postgres
#    image: postgres:16
#    volumes:
#      - ./init.sql:/data/application/init.sql
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=12345
