version: "3.7"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  db:
    container_name: postgres
    image: postgres:14.3-alpine
    networks:
      - kafka-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql

  mongodb:
    container_name: mongodb
    image: mongo:7.0
    networks:
      - kafka-net
    ports:
      - '27017:27017'

  eureka-server:
    image: eureka-server:1.0.0
    networks:
      - kafka-net
    ports:
      - 8761:8761

  passenger-service:
    image: passenger-service:1.0.0
    ports:
      - 8082:8082
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/passengerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
      - eureka-server
      - kafka

  driver-service:
    image: driver-service:1.0.0
    ports:
      - 8085:8085
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/driverdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
      - eureka-server
      - kafka

  rides-service:
    image: rides-service:1.0.0
    ports:
      - 8081:8081
    networks:
      - kafka-net
    links:
      - mongodb
    depends_on:
      - mongodb
      - eureka-server
      - kafka

  payment-service:
    image: payment-service:1.0.0
    ports:
      - 8084:8084
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/paymentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
      - eureka-server
      - kafka

  rating-service:
    image: rating-service:1.0.0
    ports:
      - 8083:8083
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ratingdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
      - eureka-server
      - kafka

  api-gateway:
    image: api-gateway:1.0.0
    ports:
      - 8765:8765
    networks:
      - kafka-net
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
