server:
  port: 8082
spring:
  application:
    name: passenger-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345
    username: postgres
    url: jdbc:postgresql://localhost:5432/passengerdb
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

