server:
  port: 8082
spring:
  application.name: passenger-service
  jackson.serialization:
    indent-output: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345
    username: postgres
    url: jdbc:postgresql://localhost:5432/passengerdb
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
feign:
  client:
    rides:
      name: rides-service
      url: http://rides-service:8081
      path: /api/v1/rides
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      sliding-window-size: 10
      minimum-number-of-calls: 5
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state:
        seconds: 5
      failure-rate-threshold: 50
      event-consumer-buffer-size: 10
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0